name: life_countdown
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version of the app
version: 1.0.0+1

# Environment
environment:
  sdk: ">=3.0.0 <4.0.0" # ใช้ Flutter SDK เวอร์ชันที่เข้ากันได้

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  dropdown_button2: ^2.0.0
  permission_handler: ^11.3.1
  gallery_saver: ^2.3.2
  path_provider: ^2.0.14 # ตรวจสอบว่าใช้เวอร์ชันล่าสุด
  screenshot: ^2.1.0
  firebase_core: ^3.10.1
  firebase_remote_config: ^5.3.1
  firebase_storage: ^12.4.1
  # Routing
  go_router: ^7.0.0
  url_launcher: ^6.1.14  # ตรวจสอบเวอร์ชันล่าสุดจาก pub.dev

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  font_awesome_flutter: ^10.5.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

flutter:
  # Generate localization files
  generate: true

  # Include Material Icons
  uses-material-design: true

  # Define assets (Uncomment and add if you use assets in the project)
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Define custom fonts (Uncomment and add if you use custom fonts)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  assets:
    - assets/images/
